apiVersion: v1
kind: PersistentVolume
metadata:
  name: anyflashcards-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  claimRef:
    name: mongo-pvc
  local:
    path: /home/ubuntu/anyflashcards_volume