apiVersion: v1
kind: PersistentVolume
metadata:
  name: anyflashcards-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  claimRef:
    name: mongo-pvc
  local:
    path: /home/ubuntu/anyflashcards_volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vh-af-kube