apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/anyflashcards_volume